local config = require("neojj.lib.jj.config")

describe("jj config", function()
  describe("ConfigEntry", function()
    it("returns a ConfigEntry from get()", function()
      local entry = config.get("neojj.test.nonexistent.key.12345")
      assert.is_not_nil(entry)
      assert.are.equal("neojj.test.nonexistent.key.12345", entry.name)
      assert.are.equal("", entry.value)
    end)

    it("is_set returns false for empty value", function()
      local entry = config.get("neojj.test.nonexistent.key.12345")
      assert.is_false(entry:is_set())
      assert.is_true(entry:is_unset())
    end)

    it("read returns nil for unset entry", function()
      local entry = config.get("neojj.test.nonexistent.key.12345")
      assert.is_nil(entry:read())
    end)

    it("type returns string for unset entry", function()
      local entry = config.get("neojj.test.nonexistent.key.12345")
      assert.are.equal("string", entry:type())
    end)
  end)

  describe("ConfigEntry:type()", function()
    it("detects boolean type for 'true'", function()
      config.set("neojj.test.config.bool", "true")
      local entry = config.get("neojj.test.config.bool")
      assert.are.equal("boolean", entry:type())
      assert.are.equal(true, entry:read())
      config.unset("neojj.test.config.bool")
    end)

    it("detects boolean type for 'false'", function()
      config.set("neojj.test.config.bool2", "false")
      local entry = config.get("neojj.test.config.bool2")
      assert.are.equal("boolean", entry:type())
      assert.are.equal(false, entry:read())
      config.unset("neojj.test.config.bool2")
    end)

    it("detects number type", function()
      config.set("neojj.test.config.num", "42")
      local entry = config.get("neojj.test.config.num")
      assert.are.equal("number", entry:type())
      assert.are.equal(42, entry:read())
      config.unset("neojj.test.config.num")
    end)

    it("detects string type", function()
      config.set("neojj.test.config.str", "hello")
      local entry = config.get("neojj.test.config.str")
      assert.are.equal("string", entry:type())
      assert.are.equal("hello", entry:read())
      config.unset("neojj.test.config.str")
    end)
  end)

  describe("set and get roundtrip", function()
    it("can set and retrieve a config value", function()
      config.set("neojj.test.config.roundtrip", "myvalue")
      local entry = config.get("neojj.test.config.roundtrip")
      assert.is_true(entry:is_set())
      assert.are.equal("myvalue", entry.value)
      config.unset("neojj.test.config.roundtrip")
    end)
  end)

  describe("unset", function()
    it("unsets a previously set value", function()
      config.set("neojj.test.config.tounset", "val")
      config.unset("neojj.test.config.tounset")
      local entry = config.get("neojj.test.config.tounset")
      assert.is_false(entry:is_set())
    end)

    it("no-ops when unsetting nonexistent key", function()
      config.unset("neojj.test.config.never.existed.12345")
    end)
  end)

  describe("update", function()
    it("sets value via update", function()
      local entry = config.get("neojj.test.config.update")
      entry:update("newval")
      local fresh = config.get("neojj.test.config.update")
      assert.are.equal("newval", fresh.value)
      config.unset("neojj.test.config.update")
    end)

    it("unsets value when update called with empty string", function()
      config.set("neojj.test.config.update2", "val")
      local entry = config.get("neojj.test.config.update2")
      entry:update("")
      local fresh = config.get("neojj.test.config.update2")
      assert.is_false(fresh:is_set())
    end)
  end)
end)
